language:
- cpp

os:
- osx
- linux

compiler:
- clang
# TODO: gcc chokes on a boost pthread usage, disabling for now.
#- gcc

#matrix:
#  exclude:
#  - os: osx
#    compiler: g++

# check environment (copied from libgit2sharp)
before_install:
- date -u
- uname -a
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/linux_before_install.sh; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_before_install.sh; fi

# make sure cmake is installed, set up latest GCC C++ compiler if necessary
install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/linux_install.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./ci/osx_install.sh; fi

# TODO: could move script to separate file
# Not running unit tests at the moment, so turn off testing, which will
# hopefully make OS X builds a bit faster
script:
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cd bin && cmake -DBUILD_TESTING=OFF -DDOWNLOAD_TOOLKITS=OFF ../src && make -j8; fi
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd bin && cmake -DBUILD_TESTING=OFF -DDOWNLOAD_TOOLKITS=OFF -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC ../src && make -j8; fi

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
